// This file is auto-generated by @hey-api/openapi-ts

export const DemoDTOSchema = {
    type: 'object',
    required: ['id', 'name'],
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        }
    }
} as const;

export const CreateDemoDTOSchema = {
    type: 'object',
    required: ['name'],
    properties: {
        name: {
            type: 'string'
        }
    }
} as const;

export const CreationResponseDTOSchema = {
    type: 'object',
    required: ['newId'],
    properties: {
        newId: {
            type: 'string',
            format: 'uuid'
        }
    }
} as const;

export const DebtTypeDTOSchema = {
    type: 'string',
    enum: ['RECEIVABLE', 'PAYABLE']
} as const;

export const DebtStatusDTOSchema = {
    type: 'string',
    enum: ['UNPAID', 'PAID']
} as const;

export const CreateDebtDTOSchema = {
    type: 'object',
    required: ['type', 'counterpartyName', 'amount', 'dueDate'],
    properties: {
        type: {
            '$ref': '#/components/schemas/DebtTypeDTO'
        },
        counterpartyName: {
            type: 'string',
            minLength: 1,
            pattern: '.*\\S.*'
        },
        amount: {
            '$ref': '#/components/schemas/MoneyDTO'
        },
        dueDate: {
            type: 'string',
            format: 'date'
        }
    }
} as const;

export const DebtDTOSchema = {
    type: 'object',
    required: ['id', 'type', 'counterpartyName', 'amount', 'dueDate', 'status', 'createdAt'],
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        type: {
            '$ref': '#/components/schemas/DebtTypeDTO'
        },
        counterpartyName: {
            type: 'string'
        },
        amount: {
            '$ref': '#/components/schemas/MoneyDTO'
        },
        dueDate: {
            type: 'string',
            format: 'date'
        },
        status: {
            '$ref': '#/components/schemas/DebtStatusDTO'
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const DebtPageDTOSchema = {
    type: 'object',
    required: ['items', 'pageNumber', 'pageSize', 'totalElements', 'totalPages'],
    properties: {
        items: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/DebtDTO'
            }
        },
        pageNumber: {
            type: 'integer',
            format: 'int32',
            minimum: 0
        },
        pageSize: {
            type: 'integer',
            format: 'int32'
        },
        totalElements: {
            type: 'integer',
            format: 'int64'
        },
        totalPages: {
            type: 'integer',
            format: 'int32'
        }
    }
} as const;

export const SubscriptionPlanStatusDTOSchema = {
    type: 'string',
    enum: ['ACTIVE', 'INACTIVE']
} as const;

export const SubscriptionPlanDurationUnitDTOSchema = {
    type: 'string',
    enum: ['WEEK', 'MONTH', 'YEAR']
} as const;

export const CreateSubscriptionPlanDTOSchema = {
    type: 'object',
    required: ['status', 'durationValue', 'durationUnit', 'price'],
    properties: {
        status: {
            '$ref': '#/components/schemas/SubscriptionPlanStatusDTO'
        },
        durationValue: {
            type: 'integer',
            format: 'int32',
            minimum: 1
        },
        durationUnit: {
            '$ref': '#/components/schemas/SubscriptionPlanDurationUnitDTO'
        },
        price: {
            '$ref': '#/components/schemas/MoneyDTO'
        }
    }
} as const;

export const TransactionTypeDTOSchema = {
    type: 'string',
    enum: ['INCOMING', 'EXPENSE']
} as const;

export const TransactionCategoryDTOSchema = {
    type: 'string',
    enum: ['STOCK', 'TRANSPORT', 'FOOD', 'PHONE_CREDIT', 'RENT', 'EMPLOYEE_SALARY', 'SALE', 'SERVICE_PROVIDED', 'SALARY', 'OTHER']
} as const;

export const CreateTransactionDTOSchema = {
    type: 'object',
    required: ['type', 'category', 'amount'],
    properties: {
        type: {
            '$ref': '#/components/schemas/TransactionTypeDTO'
        },
        category: {
            '$ref': '#/components/schemas/TransactionCategoryDTO'
        },
        otherCategoryDetail: {
            type: 'string',
            description: 'Required when category is OTHER'
        },
        amount: {
            type: 'number',
            minimum: 0,
            exclusiveMinimum: true
        },
        description: {
            type: 'string'
        }
    }
} as const;

export const TransactionDTOSchema = {
    type: 'object',
    required: ['id', 'type', 'category', 'amount', 'createdAt'],
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        type: {
            '$ref': '#/components/schemas/TransactionTypeDTO'
        },
        category: {
            '$ref': '#/components/schemas/TransactionCategoryDTO'
        },
        otherCategoryDetail: {
            type: 'string'
        },
        amount: {
            type: 'number'
        },
        description: {
            type: 'string'
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const TransactionPageDTOSchema = {
    type: 'object',
    required: ['items', 'pageNumber', 'pageSize', 'totalElements', 'totalPages'],
    properties: {
        items: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/TransactionDTO'
            }
        },
        pageNumber: {
            type: 'integer',
            format: 'int32',
            minimum: 0
        },
        pageSize: {
            type: 'integer',
            format: 'int32',
            minimum: 1
        },
        totalElements: {
            type: 'integer',
            format: 'int64'
        },
        totalPages: {
            type: 'integer',
            format: 'int32'
        }
    }
} as const;

export const MoneyDTOSchema = {
    type: 'object',
    required: ['value', 'currency'],
    properties: {
        value: {
            type: 'number'
        },
        currency: {
            type: 'string',
            minLength: 3,
            maxLength: 3,
            pattern: '^[A-Z]{3}$'
        }
    }
} as const;