// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-axios';
import type { FetchAllDemo_Data, FetchAllDemo_Response, CreateDemo_Data, CreateDemo_Response, FetchDemoById_Data, FetchDemoById_Response, FetchTransactions_Data, FetchTransactions_Response, CreateTransaction_Data, CreateTransaction_Response, FetchDebtsByType_Data, FetchDebtsByType_Response, CreateDebt_Data, CreateDebt_Response, MarkDebtAsPaid_Data, MarkDebtAsPaid_Response, CreateSubscriptionPlan_Data, CreateSubscriptionPlan_Response, FetchTransactionBalance_Data, FetchTransactionBalance_Response, FetchTransactionAmountByType_Data, FetchTransactionAmountByType_Response } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
};

export class DemoService {
    /**
     * Fetch all Demos
     * Fetch all Demos
     */
    public static fetchAllDemo<ThrowOnError extends boolean = false>(options?: Options<FetchAllDemo_Data, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<FetchAllDemo_Response, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/demo',
            ...options
        });
    }
    
    /**
     * Create a new Demo
     * Create a new Demo
     */
    public static createDemo<ThrowOnError extends boolean = false>(options: Options<CreateDemo_Data, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<CreateDemo_Response, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/demo',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Fetch demo by id
     * Fetch demo by id
     */
    public static fetchDemoById<ThrowOnError extends boolean = false>(options: Options<FetchDemoById_Data, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<FetchDemoById_Response, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/demo/{demoId}',
            ...options
        });
    }
    
}

export class TransactionService {
    /**
     * Fetch current user transactions
     * Fetch current user transactions with optional type filtering and pagination
     */
    public static fetchTransactions<ThrowOnError extends boolean = false>(options?: Options<FetchTransactions_Data, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<FetchTransactions_Response, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/transaction',
            ...options
        });
    }
    
    /**
     * Create a new transaction
     * Create a new transaction
     */
    public static createTransaction<ThrowOnError extends boolean = false>(options: Options<CreateTransaction_Data, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<CreateTransaction_Response, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/transaction',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Fetch current user balance over a period
     * Compute the current user balance over a period using incoming transactions minus expenses
     */
    public static fetchTransactionBalance<ThrowOnError extends boolean = false>(options: Options<FetchTransactionBalance_Data, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<FetchTransactionBalance_Response, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/transaction/balance',
            ...options
        });
    }
    
    /**
     * Fetch current user transaction amount by type over a period
     * Compute the sum of transaction amounts for the current user, filtered by type and period
     */
    public static fetchTransactionAmountByType<ThrowOnError extends boolean = false>(options: Options<FetchTransactionAmountByType_Data, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<FetchTransactionAmountByType_Response, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/transaction/amount',
            ...options
        });
    }
    
}

export class DebtService {
    /**
     * Fetch current user debts
     * Fetch current user debts with optional type filtering and pagination
     */
    public static fetchDebtsByType<ThrowOnError extends boolean = false>(options?: Options<FetchDebtsByType_Data, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<FetchDebtsByType_Response, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/debt',
            ...options
        });
    }
    
    /**
     * Create a new debt
     * Create a new debt for the current user
     */
    public static createDebt<ThrowOnError extends boolean = false>(options: Options<CreateDebt_Data, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<CreateDebt_Response, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/debt',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Mark a debt as paid
     * Mark the current user debt as paid and create the related transaction
     */
    public static markDebtAsPaid<ThrowOnError extends boolean = false>(options: Options<MarkDebtAsPaid_Data, ThrowOnError>) {
        return (options.client ?? _heyApiClient).put<MarkDebtAsPaid_Response, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/debt/{debtId}/paid',
            ...options
        });
    }
    
}

export class SubscriptionPlanService {
    /**
     * Create a new subscription plan
     * Create a new subscription plan
     */
    public static createSubscriptionPlan<ThrowOnError extends boolean = false>(options: Options<CreateSubscriptionPlan_Data, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<CreateSubscriptionPlan_Response, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/subscription-plan',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
}