// This file is auto-generated by @hey-api/openapi-ts

export type DemoDTO = {
    id: string;
    name: string;
};

export type CreateDemoDTO = {
    name: string;
};

export type CreationResponseDTO = {
    newId: string;
};

export type DebtTypeDTO = 'RECEIVABLE' | 'PAYABLE';

export type DebtStatusDTO = 'UNPAID' | 'PAID';

export type CreateDebtDTO = {
    type: DebtTypeDTO;
    counterpartyName: string;
    amount: MoneyDTO;
    dueDate: string;
};

export type DebtDTO = {
    id: string;
    type: DebtTypeDTO;
    counterpartyName: string;
    amount: MoneyDTO;
    dueDate: string;
    status: DebtStatusDTO;
    createdAt: string;
};

export type DebtPageDTO = {
    items: Array<DebtDTO>;
    pageNumber: number;
    pageSize: number;
    totalElements: number;
    totalPages: number;
};

export type SubscriptionPlanStatusDTO = 'ACTIVE' | 'INACTIVE';

export type SubscriptionPlanDurationUnitDTO = 'WEEK' | 'MONTH' | 'YEAR';

export type CreateSubscriptionPlanDTO = {
    status: SubscriptionPlanStatusDTO;
    durationValue: number;
    durationUnit: SubscriptionPlanDurationUnitDTO;
    price: MoneyDTO;
};

export type TransactionTypeDTO = 'INCOMING' | 'EXPENSE';

export type TransactionCategoryDTO = 'STOCK' | 'TRANSPORT' | 'FOOD' | 'PHONE_CREDIT' | 'RENT' | 'EMPLOYEE_SALARY' | 'SALE' | 'SERVICE_PROVIDED' | 'SALARY' | 'OTHER';

export type CreateTransactionDTO = {
    type: TransactionTypeDTO;
    category: TransactionCategoryDTO;
    /**
     * Required when category is OTHER
     */
    otherCategoryDetail?: string;
    amount: number;
    description?: string;
};

export type TransactionDTO = {
    id: string;
    type: TransactionTypeDTO;
    category: TransactionCategoryDTO;
    otherCategoryDetail?: string;
    amount: number;
    description?: string;
    createdAt: string;
};

export type TransactionPageDTO = {
    items: Array<TransactionDTO>;
    pageNumber: number;
    pageSize: number;
    totalElements: number;
    totalPages: number;
};

export type MoneyDTO = {
    value: number;
    currency: string;
};

export type FetchAllDemo_Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/demo';
};

export type FetchAllDemo_Responses = {
    /**
     * successful operation
     */
    200: Array<DemoDTO>;
};

export type FetchAllDemo_Response = FetchAllDemo_Responses[keyof FetchAllDemo_Responses];

export type CreateDemo_Data = {
    body: CreateDemoDTO;
    path?: never;
    query?: never;
    url: '/demo';
};

export type CreateDemo_Responses = {
    /**
     * successful operation
     */
    201: CreationResponseDTO;
};

export type CreateDemo_Response = CreateDemo_Responses[keyof CreateDemo_Responses];

export type FetchDemoById_Data = {
    body?: never;
    path: {
        /**
         * represents the id of demo to fetch.
         */
        demoId: string;
    };
    query?: never;
    url: '/demo/{demoId}';
};

export type FetchDemoById_Errors = {
    /**
     * KAPITA-404-001
     */
    404: unknown;
};

export type FetchDemoById_Responses = {
    /**
     * successful operation
     */
    200: DemoDTO;
};

export type FetchDemoById_Response = FetchDemoById_Responses[keyof FetchDemoById_Responses];

export type FetchTransactions_Data = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Transaction type to filter. When omitted, all transaction types are returned.
         */
        type?: TransactionTypeDTO;
        /**
         * Zero-based page number. Defaults to 0.
         */
        pageNumber?: number;
        /**
         * Number of items per page. Defaults to 10.
         */
        pageSize?: number;
    };
    url: '/transaction';
};

export type FetchTransactions_Responses = {
    /**
     * successful operation
     */
    200: TransactionPageDTO;
};

export type FetchTransactions_Response = FetchTransactions_Responses[keyof FetchTransactions_Responses];

export type CreateTransaction_Data = {
    body: CreateTransactionDTO;
    path?: never;
    query?: never;
    url: '/transaction';
};

export type CreateTransaction_Responses = {
    /**
     * successful operation
     */
    201: CreationResponseDTO;
};

export type CreateTransaction_Response = CreateTransaction_Responses[keyof CreateTransaction_Responses];

export type FetchDebtsByType_Data = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Debt type to filter. When omitted, all debt types are returned.
         */
        type?: DebtTypeDTO;
        /**
         * Zero-based page number. Defaults to 0.
         */
        pageNumber?: number;
        /**
         * Number of items per page. Defaults to 10.
         */
        pageSize?: number;
    };
    url: '/debt';
};

export type FetchDebtsByType_Responses = {
    /**
     * successful operation
     */
    200: DebtPageDTO;
};

export type FetchDebtsByType_Response = FetchDebtsByType_Responses[keyof FetchDebtsByType_Responses];

export type CreateDebt_Data = {
    body: CreateDebtDTO;
    path?: never;
    query?: never;
    url: '/debt';
};

export type CreateDebt_Responses = {
    /**
     * successful operation
     */
    201: CreationResponseDTO;
};

export type CreateDebt_Response = CreateDebt_Responses[keyof CreateDebt_Responses];

export type MarkDebtAsPaid_Data = {
    body?: never;
    path: {
        /**
         * Debt identifier.
         */
        debtId: string;
    };
    query?: never;
    url: '/debt/{debtId}/paid';
};

export type MarkDebtAsPaid_Errors = {
    /**
     * KAPITA-404-002
     */
    404: unknown;
};

export type MarkDebtAsPaid_Responses = {
    /**
     * successful operation
     */
    200: DebtDTO;
};

export type MarkDebtAsPaid_Response = MarkDebtAsPaid_Responses[keyof MarkDebtAsPaid_Responses];

export type CreateSubscriptionPlan_Data = {
    body: CreateSubscriptionPlanDTO;
    path?: never;
    query?: never;
    url: '/subscription-plan';
};

export type CreateSubscriptionPlan_Responses = {
    /**
     * successful operation
     */
    201: CreationResponseDTO;
};

export type CreateSubscriptionPlan_Response = CreateSubscriptionPlan_Responses[keyof CreateSubscriptionPlan_Responses];

export type FetchTransactionBalance_Data = {
    body?: never;
    path?: never;
    query: {
        /**
         * Inclusive period start date.
         */
        startDate: string;
        /**
         * Inclusive period end date.
         */
        endDate: string;
    };
    url: '/transaction/balance';
};

export type FetchTransactionBalance_Responses = {
    /**
     * successful operation
     */
    200: MoneyDTO;
};

export type FetchTransactionBalance_Response = FetchTransactionBalance_Responses[keyof FetchTransactionBalance_Responses];

export type FetchTransactionAmountByType_Data = {
    body?: never;
    path?: never;
    query: {
        /**
         * Inclusive period start date.
         */
        startDate: string;
        /**
         * Inclusive period end date.
         */
        endDate: string;
        /**
         * Transaction type to aggregate.
         */
        type: TransactionTypeDTO;
    };
    url: '/transaction/amount';
};

export type FetchTransactionAmountByType_Responses = {
    /**
     * successful operation
     */
    200: MoneyDTO;
};

export type FetchTransactionAmountByType_Response = FetchTransactionAmountByType_Responses[keyof FetchTransactionAmountByType_Responses];

export type ClientOptions = {
    baseURL: `${string}://https` | `${string}://http` | (string & {});
};