// This file is auto-generated by @hey-api/openapi-ts

export const DemoDTOSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        }
    }
} as const;

export const UserDTOSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        userName: {
            type: 'string'
        },
        email: {
            type: 'string',
            format: 'email'
        },
        firstName: {
            type: 'string'
        },
        lastName: {
            type: 'string'
        },
        birthDate: {
            type: 'string',
            format: 'date'
        },
        address: {
            '$ref': '#/components/schemas/AddressDTO'
        }
    }
} as const;

export const AddressDTOSchema = {
    properties: {
        city: {
            type: 'string',
            description: 'city of address'
        }
    }
} as const;

export const CreateUserSchema = {
    required: ['userName', 'email', 'password'],
    type: 'object',
    properties: {
        userName: {
            type: 'string'
        },
        email: {
            type: 'string',
            format: 'email'
        },
        password: {
            type: 'string',
            writeOnly: true
        },
        firstName: {
            type: 'string'
        },
        lastName: {
            type: 'string'
        },
        birthDate: {
            type: 'string',
            format: 'date'
        },
        address: {
            '$ref': '#/components/schemas/AddressDTO'
        }
    }
} as const;

export const CreateRoleDTOSchema = {
    required: ['name'],
    properties: {
        name: {
            type: 'string',
            description: 'name of role'
        },
        description: {
            type: 'string',
            description: 'description of role'
        }
    }
} as const;

export const RefreshTokenRequestSchema = {
    required: ['refreshToken'],
    type: 'object',
    properties: {
        refreshToken: {
            type: 'string',
            writeOnly: true
        }
    }
} as const;

export const RefreshTokenResponseSchema = {
    type: 'object',
    properties: {
        accessToken: {
            type: 'string'
        },
        tokenType: {
            type: 'string'
        },
        expiresIn: {
            type: 'integer',
            format: 'int64'
        },
        refreshToken: {
            type: 'string'
        },
        refreshExpiresIn: {
            type: 'integer',
            format: 'int64'
        },
        scope: {
            type: 'string'
        }
    }
} as const;

export const ResetPasswordRequestSchema = {
    required: ['resetToken', 'newPassword'],
    type: 'object',
    properties: {
        resetToken: {
            type: 'string',
            writeOnly: true
        },
        newPassword: {
            type: 'string',
            format: 'password',
            minLength: 6,
            writeOnly: true
        }
    }
} as const;