// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-axios';
import type { FetchAllDemo_Data, FetchAllDemo_Response, CreateDemo_Data, CreateDemo_Response, Register_Data, Register_Response, RefreshToken_Data, RefreshToken_Response, Logout_Data, Logout_Response, ResetPasswordWithToken_Data, ResetPasswordWithToken_Response, FetchAllUsers_Data, FetchAllUsers_Response, CreateRole_Data, CreateRole_Response, RemoveRoleToUser_Data, RemoveRoleToUser_Response, AddRoleToUser_Data, AddRoleToUser_Response } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
};

export class DemoService {
    /**
     * Demo Summary
     * Demo Description
     */
    public static fetchAllDemo<ThrowOnError extends boolean = false>(options?: Options<FetchAllDemo_Data, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<FetchAllDemo_Response, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/demo',
            ...options
        });
    }
    
    /**
     * Create a new Demo
     * Creates a new Demo with the provided data
     */
    public static createDemo<ThrowOnError extends boolean = false>(options: Options<CreateDemo_Data, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<CreateDemo_Response, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/demo',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
}

export class UserService {
    /**
     * register user
     * register user
     */
    public static register<ThrowOnError extends boolean = false>(options: Options<Register_Data, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<Register_Response, unknown, ThrowOnError>({
            url: '/register',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * get user info
     * get user info including id, username, and all roles
     */
    public static fetchAllUsers<ThrowOnError extends boolean = false>(options?: Options<FetchAllUsers_Data, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<FetchAllUsers_Response, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/user',
            ...options
        });
    }
    
    /**
     * Remove roles to a user
     * Remove roles  to a user
     */
    public static removeRoleToUser<ThrowOnError extends boolean = false>(options: Options<RemoveRoleToUser_Data, ThrowOnError>) {
        return (options.client ?? _heyApiClient).delete<RemoveRoleToUser_Response, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/users/{userId}/roles/{roleName}',
            ...options
        });
    }
    
    /**
     * Add roles to a user
     */
    public static addRoleToUser<ThrowOnError extends boolean = false>(options: Options<AddRoleToUser_Data, ThrowOnError>) {
        return (options.client ?? _heyApiClient).put<AddRoleToUser_Response, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/users/{userId}/roles/{roleName}',
            ...options
        });
    }
    
}

export class AuthService {
    /**
     * Refresh JWT access token
     * Uses a refresh token to obtain a new JWT access token from Keycloak
     */
    public static refreshToken<ThrowOnError extends boolean = false>(options: Options<RefreshToken_Data, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<RefreshToken_Response, unknown, ThrowOnError>({
            url: '/auth/refresh',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Logout user session
     * Invalidates refresh token and terminates Keycloak user session
     */
    public static logout<ThrowOnError extends boolean = false>(options: Options<Logout_Data, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<Logout_Response, unknown, ThrowOnError>({
            url: '/auth/logout',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Reset password with token
     * Validates reset token and updates user password
     */
    public static resetPasswordWithToken<ThrowOnError extends boolean = false>(options: Options<ResetPasswordWithToken_Data, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<ResetPasswordWithToken_Response, unknown, ThrowOnError>({
            url: '/auth/reset-password',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
}

export class RoleService {
    /**
     * create new role
     * create role
     */
    public static createRole<ThrowOnError extends boolean = false>(options: Options<CreateRole_Data, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<CreateRole_Response, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/role',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
}