// This file is auto-generated by @hey-api/openapi-ts

export type DemoDTO = {
    id?: string;
    name?: string;
};

export type UserDTO = {
    id?: string;
    userName?: string;
    email?: string;
    firstName?: string;
    lastName?: string;
    birthDate?: string;
    address?: AddressDTO;
};

export type AddressDTO = {
    /**
     * city of address
     */
    city?: string;
};

export type CreateUser = {
    userName: string;
    email: string;
    password: string;
    firstName?: string;
    lastName?: string;
    birthDate?: string;
    address?: AddressDTO;
};

export type CreateRoleDTO = {
    /**
     * name of role
     */
    name: string;
    /**
     * description of role
     */
    description?: string;
};

export type RefreshTokenRequest = {
    refreshToken: string;
};

export type RefreshTokenResponse = {
    accessToken?: string;
    tokenType?: string;
    expiresIn?: number;
    refreshToken?: string;
    refreshExpiresIn?: number;
    scope?: string;
};

export type ResetPasswordRequest = {
    resetToken: string;
    newPassword: string;
};

export type FetchAllDemo_Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/demo';
};

export type FetchAllDemo_Errors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type FetchAllDemo_Responses = {
    /**
     * successful operation
     */
    200: Array<DemoDTO>;
};

export type FetchAllDemo_Response = FetchAllDemo_Responses[keyof FetchAllDemo_Responses];

export type CreateDemo_Data = {
    /**
     * Demo object to be created
     */
    body: DemoDTO;
    path?: never;
    query?: never;
    url: '/demo';
};

export type CreateDemo_Errors = {
    /**
     * Invalid input
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
};

export type CreateDemo_Responses = {
    /**
     * Demo created successfully
     */
    201: string;
};

export type CreateDemo_Response = CreateDemo_Responses[keyof CreateDemo_Responses];

export type Register_Data = {
    body: CreateUser;
    path?: never;
    query?: never;
    url: '/register';
};

export type Register_Errors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * this username already exist
     */
    409: unknown;
};

export type Register_Responses = {
    /**
     * User created successfully
     */
    201: string;
};

export type Register_Response = Register_Responses[keyof Register_Responses];

export type RefreshToken_Data = {
    body: RefreshTokenRequest;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type RefreshToken_Errors = {
    /**
     * Invalid or expired refresh token
     */
    400: unknown;
    /**
     * Unauthorized client
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Keycloak unavailable
     */
    502: unknown;
};

export type RefreshToken_Responses = {
    /**
     * Token refreshed successfully
     */
    200: RefreshTokenResponse;
};

export type RefreshToken_Response = RefreshToken_Responses[keyof RefreshToken_Responses];

export type Logout_Data = {
    body: RefreshTokenRequest;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type Logout_Errors = {
    /**
     * Invalid or expired refresh token
     */
    400: unknown;
    /**
     * Unauthorized client
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Keycloak unavailable
     */
    502: unknown;
};

export type Logout_Responses = {
    /**
     * Logout completed successfully
     */
    204: void;
};

export type Logout_Response = Logout_Responses[keyof Logout_Responses];

export type ResetPasswordWithToken_Data = {
    body: ResetPasswordRequest;
    path?: never;
    query?: never;
    url: '/auth/reset-password';
};

export type ResetPasswordWithToken_Errors = {
    /**
     * Invalid or expired reset token, or invalid password
     */
    400: unknown;
    /**
     * Unauthorized client
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Keycloak unavailable
     */
    502: unknown;
};

export type ResetPasswordWithToken_Responses = {
    /**
     * Password reset completed successfully
     */
    204: void;
};

export type ResetPasswordWithToken_Response = ResetPasswordWithToken_Responses[keyof ResetPasswordWithToken_Responses];

export type FetchAllUsers_Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user';
};

export type FetchAllUsers_Errors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * User not found
     */
    404: unknown;
};

export type FetchAllUsers_Responses = {
    /**
     * successful operation
     */
    200: Array<UserDTO>;
};

export type FetchAllUsers_Response = FetchAllUsers_Responses[keyof FetchAllUsers_Responses];

export type CreateRole_Data = {
    body: CreateRoleDTO;
    path?: never;
    query?: never;
    url: '/role';
};

export type CreateRole_Errors = {
    /**
     * this role already exist
     */
    409: unknown;
};

export type CreateRole_Responses = {
    /**
     * Role created successfully
     */
    201: string;
};

export type CreateRole_Response = CreateRole_Responses[keyof CreateRole_Responses];

export type RemoveRoleToUser_Data = {
    body?: never;
    path: {
        userId: string;
        /**
         * The name of the role to be removed
         */
        roleName: string;
    };
    query?: never;
    url: '/users/{userId}/roles/{roleName}';
};

export type RemoveRoleToUser_Errors = {
    /**
     * Invalid role name
     */
    400: unknown;
    /**
     * User/role not found
     */
    404: unknown;
};

export type RemoveRoleToUser_Responses = {
    /**
     * Roles removed successfully
     */
    204: void;
};

export type RemoveRoleToUser_Response = RemoveRoleToUser_Responses[keyof RemoveRoleToUser_Responses];

export type AddRoleToUser_Data = {
    body?: never;
    path: {
        /**
         * The user ID
         */
        userId: string;
        /**
         * The name of the role to be added
         */
        roleName: string;
    };
    query?: never;
    url: '/users/{userId}/roles/{roleName}';
};

export type AddRoleToUser_Errors = {
    /**
     * Invalid role name
     */
    400: unknown;
    /**
     * User/role not found
     */
    404: unknown;
};

export type AddRoleToUser_Responses = {
    /**
     * Roles added successfully
     */
    204: void;
};

export type AddRoleToUser_Response = AddRoleToUser_Responses[keyof AddRoleToUser_Responses];

export type ClientOptions = {
    baseURL: 'https://localhost:8089' | 'http://localhost:8089' | (string & {});
};